config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :participants, :clinics
  root to: 'arms#index'
  resources :arms do
    resources :participants
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arm.rb
class Arm < ApplicationRecord
    has_many :participants
    validates :name, :limit, presence: true

    validates :name, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z\s]+\Z/,
  message: "only allows letters" }

  validates :limit, numericality: { only_integer: true }
end

app/models/clinic.rb
# frozen_string_literal: true

class Clinic < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord

    has_many :clinics

    validates :name, :specification, presence: true

    validates :name, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z\s]+\Z/,
  message: "only allows letters" }

end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  belongs_to :arm
  validates :name, :age, :gender, presence: true

  validates :gender, inclusion: { in: %w[Male Female],
                                  message: 'Gender must be either male or female' }

  validates :name, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z\s]+\Z/,
  message: "only allows letters" }

  validates :age, numericality: { only_integer: true }
  before_validation :handle_gender
  after_validation :method_after_validation

  before_save :method_before_save
  after_save :method_after_save

  before_create :method_before_create
  after_create :method_after_create

  private

  def handle_gender
    # if self.gender.downcase.in? ['male', 'm']
    #     self.gender = 'Male'
    # end
    self.gender = (gender.downcase.in? %w[male m]) ? 'Male' : gender
    self.gender = (gender.downcase.in? %w[female f]) ? 'Female' : gender
  end

  def method_after_validation
    puts '====================================='
    puts 'we are in after validation method'
    puts '====================================='
  end

  def method_before_save
    puts '====================================='
    puts 'we are in before save method'
    puts '====================================='
  end

  def method_after_save
    puts '====================================='
    puts 'we are in after save method'
    puts '====================================='
  end

  def method_before_create
    puts '====================================='
    puts 'we are in before create method'
    puts '====================================='
  end

  def method_after_create
    puts '====================================='
    puts 'we are in after create method'
    puts '====================================='
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/arms_controller.rb
class ArmsController < ApplicationController

  def index
    @arms = Arm.all
  end

  def new
    @arm ||= Arm.new
  end

  def show; end

  def update; end

  def create
    @arm = Arm.new(permit_params)
    if @arm.save
      redirect_to arms_path
    else
      render :new
    end
  end

  def destroy
    @arm = Arm.find(params[:id])
    redirect_to arms_path if @arm.destroy
  end

  private

  def permit_params
    params.require(:arm).permit(:name, :limit)
  end
end

app/controllers/clinics_controller.rb
# frozen_string_literal: true

class ClinicsController < ApplicationController
  def index
    @clinics = Clinic.all
  end

  def new
    @clinic ||= Clinic.new
  end

  def show; end

  def update; end

  def create
    # binding.pry
    required_params = params.require(:clinic).permit(:name, :location)
    # binding.pry
    @clinic = Clinic.new(required_params)
    if @clinic.save
      redirect_to clinics_path
    else
      render :new
    end
  end

  def destroy; end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
end

app/controllers/participants_controller.rb
# frozen_string_literal: true

class ParticipantsController < ApplicationController
  before_action :find_arm, only: [:index, :destroy, :new, :create]

  def index
    @participants = @arm.participants
  end

  def new
    @participant ||= @arm.participants.new
  end

  def show; end

  def update; end

  def create
    @participant = @arm.participants.new(permit_params)
    if @participant.save
      redirect_to arm_participants_path(@arm.id)
    else
      render :new
    end
  end

  def destroy
    @participant = Participant.find(params[:id])
    redirect_to arm_participants_path(@arm.id) if @participant.destroy
  end

  private

  def permit_params
    params.require(:participant).permit(:name, :age, :gender, :arm_id)
  end

  def find_arm
    @arm = Arm.find_by(id: params[:arm_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/arms_helper.rb
module ArmsHelper
end

app/helpers/clinics_helper.rb
# frozen_string_literal: true

module ClinicsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/participants_helper.rb
# frozen_string_literal: true

module ParticipantsHelper
end

app/views/arms/index.html.erb
<h1> Show All the arms </h1>

<%= link_to "Create new arm", new_arm_path %>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Limit</th>
  </tr>
  <% @arms.each do |arm| %>
    <tr>
      <td><%= arm.id %></td>
      <td><%= arm.name %></td>
      <td><%= arm.limit %></td>
      <td><%= link_to "Edit Arm", edit_arm_path(arm.id) %></td>
      <td><%= link_to "Delete", method: :delete %></td>
      <td><%= link_to "Participants", arm_participants_path(arm.id) %></td>
      </ br>
    </tr>
  <% end %>
</table>

app/views/arms/new.html.erb
<h1>New Arm</h1>

<% if @arm.errors.present? %>
  <ul>
    <% @arm.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @arm, url: '/arms', local: true) do |f| %>
    <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.label :limit %>
    <%= f.text_field :limit %>
    </p>
    <%= f.submit 'create' %>
<% end %>

app/views/clinics/index.html.erb
<h1>Clinic</h1>
<%= link_to "Add Clinic", new_clinic_path %>
<table>
    <tr>
    <th>Name</th>
    <th>Location</th>
    </tr>
<tr>
<% @clinics.each do |clinic| %>
   <td> <%= clinic.name %> </td>
    <td> <%= clinic.location %> </td>
    <br>
    </tr>
<% end %>

</table>

app/views/clinics/new.html.erb
<h1>New Clinic</h1>

<% if @clinic.errors.present? %>
  <ul>
    <% @clinic.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @clinic, url: '/clinics', local: true) do |f| %>
    <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
    </p>
    <%= f.submit 'create' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MimicMedidata</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participants/index.html.erb
<h1> Show All the Participants </h1>
<%= link_to "Arms_List", arms_path %>
<%= link_to "Create new participant", new_arm_participant_path(@arm.id) %>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Age</th>
    <th>Gender</th>
    <th>Arm Name</th>
  </tr>
  <% @participants.each do |participant| %>
    <tr>
      <td><%= participant.id %></td>
      <td><%= participant.name %></td>
      <td><%= participant.age %></td>
      <td><%= participant.gender %></td>
      <td><%= participant.arm.name if participant.arm %></td>
      <td><%= link_to "Edit Participant", edit_arm_participant_path(@arm.id, participant.id) %></td>
      </ br>
    </tr>
  <% end %>

</table>

app/views/participants/new.html.erb
<h2> Create Participant </h2>
<% if @participant.errors.present? %>
  <ul>
    <% @participant.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for(@participant, url: arm_participants_path(@arm.id)) do |f| %>
  <p>
  <%= f.label 'Name' %>
  <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label 'Age' %>
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label 'Gender' %>
    <%= f.text_field :gender %>
  </p>
  <%= f.submit 'Create' %>
<% end %>